In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC #classification
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train , X_test , y_train , y_test =  train_test_split(digits.data , digits.target , test_size=0.3)

In [5]:
lr = LogisticRegression()
lr.fit(X_train , y_train)
lr.score(X_test , y_test)

C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [6]:
svm = SVC()
svm.fit(X_train , y_train)
svm.score(X_test , y_test)

0.9833333333333333

In [7]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train , y_train)
rf.score(X_test , y_test)

0.9685185185185186

In [8]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)

In [9]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model ,X_train , X_test , y_train , y_test):
    model.fit(X_train ,y_train)
    return model.score(X_test , y_test)

In [11]:
get_score( SVC() , X_train ,X_test  , y_train ,y_test )

0.9833333333333333

In [12]:
get_score( RandomForestClassifier() , X_train ,X_test  , y_train ,y_test )

0.9685185185185186

In [13]:
get_score( LogisticRegression() , X_train ,X_test  , y_train ,y_test )

C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [18]:


scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

In [19]:
scores_l

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [20]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [21]:
scores_rf

[0.9348914858096828, 0.9582637729549248, 0.9265442404006677]

In [26]:
cross_val_score(LogisticRegression() , digits.data , digits.target)

C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC() , digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier() , digits.data , digits.target)

array([0.93055556, 0.90555556, 0.95543175, 0.96657382, 0.92479109])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=100) , digits.data , digits.target)

array([0.93333333, 0.93333333, 0.94986072, 0.9637883 , 0.9275766 ])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=50) , digits.data , digits.target)

array([0.93888889, 0.92222222, 0.95543175, 0.95821727, 0.9275766 ])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=10) , digits.data , digits.target)

array([0.88611111, 0.87222222, 0.93314763, 0.93314763, 0.90807799])