In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as f:
    pickle.dump(model , f)

In [11]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [14]:
mp.predict([[5000]])

array([859554.79452055])

In [22]:
from sklearn.externals import joblib
from sklearn import *

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\KRM0201517\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [26]:
joblib.dump(model , 'model_joblib')

NameError: name 'joblib' is not defined

In [ ]:
mj = joblib.load('model_joblib')