# Linear Regression Multiple Variables

In [6]:
#import packages
import numpy as np
import pandas as pd
from sklearn import linear_model
import math

In [2]:
#read_data
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
#information dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      5 non-null      int64  
 1   bedrooms  4 non-null      float64
 2   age       5 non-null      int64  
 3   price     5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 288.0 bytes


In [4]:
#describe data
df.describe()

area  bedrooms       age          price
count     5.000000  4.000000   5.00000       5.000000
mean   3280.000000  3.750000  18.20000  616000.000000
std     540.370243  0.957427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.500000  18.00000  595000.000000
75%    3600.000000  4.250000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000

In [7]:
# median bedrooms
median_bedrooms  =math.floor(df.bedrooms.median())
median_bedrooms

3

In [8]:
#fill value
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
#model Linear Redgression
model = linear_model.LinearRegression()
model.fit( df[['area','bedrooms','age']] , df.price  )

LinearRegression()

In [11]:
model.coef_  #slope   # m

array([   137.25, -26025.  ,  -6825.  ])

In [12]:
model.intercept_  #b #intercept

383724.9999999998

In [17]:
#            'area','bedrooms','age'
model.predict([[3000,    3,    40]]  )

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [19]:
model.coef_[0]*3000 + model.coef_[1]*3+model.coef_[2]*40 +model.intercept_

444400.0

In [20]:
#example another
model.predict([[2500,    4,  5]]  )

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [21]:
model.coef_[0]*2500 +model.coef_[1]*4  + model.coef_[2]*5 +model.intercept_

588624.9999999999