# Load data

In [21]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [22]:
df = pd.read_csv('homeprices.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [23]:
import math
med_bedrooms = math.floor(df.bedrooms.median())
med_bedrooms

3

In [24]:
df.bedrooms=df.bedrooms.fillna(med_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [25]:
from sklearn.linear_model import *

In [30]:
y=df[['price']]
x=df[['area','bedrooms','age']]

In [32]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

prce = m1 * area +m2 *bedrooms + m3 * age +b

In [34]:
model.coef_  #m1 ,m2 ,m3

array([[   137.25, -26025.  ,  -6825.  ]])

In [36]:
model.intercept_  #b

array([383725.])

In [49]:
model.predict([[3000,3,40]])

array([[444400.]])

In [52]:
137.25 * 3000 + 3* -26025 + 40 * -6825 + 383725   ### price = m1 * area +m2 *bedrooms + m3 * age +b

444400.0

In [53]:
model.predict([[2500,4,5]])

array([[588625.]])